### ISSUE TITLE
App crush and recovery

### ISSUE THREAD

**Issue by orith94** [i-e-b/DiskQueue#32]
Hello, 

I'm encountering an issue with my app that using DiskQueue. Everything works well when it closes properly because I've implemented proper disposal for my queue. However, if the app closes abruptly, the queue remains locked indefinitely. Do you have any suggestions on how to handle this situation?

Thank you, Orit

**Comment by i-e-b** [comment]
Hi. Can you confirm what version you are using?

Recent versions should try and recover locks that were put in place by processes that are ended ( https://github.com/i-e-b/DiskQueue/blob/master/src/DiskQueue/Implementation/StandardFileDriver.cs#L76 )

Otherwise, it should be possible to delete the lock file if you're sure the process is no longer using it.

**Comment by orith94** [comment]
I'm using version 1.7.1 on Linux with Kubernetes
When the Container crush and restart the file lock and not recover ...

**Comment by i-e-b** [comment]
It's possible that the file lock is being created with permissions for the first container that are not accessible to the second? Can you try deleting the lock file from within the container at start-up, or handling this directly with Kubernetes?

**Comment by i-e-b** [comment]
Closing this for now. Please re-open if you have more details.
